// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
"use client";
import {
  stdin_default
} from "./chunks/chunk-CFC2XNCQ.js";
import "./chunks/chunk-NI3BWCIH.js";
import "./chunks/chunk-6AICCZML.js";
import {
  routes
} from "./chunks/chunk-VG7AXKTA.js";

// virtual:button
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes,
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: void 0,
      locale,
      locales
    }
  );
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes,
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: void 0,
      locale,
      locales
    }
  );
};
Object.assign(ComponentWithRoot, stdin_default);
var button_default = ComponentWithRoot;
export {
  button_default as default
};
