// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
"use client";
import {
  routes
} from "./chunks/chunk-VG7AXKTA.js";

// virtual:memoji
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gzcvIU2DusN5vOaROhWp/aLsAXuvGorcl0XPX9HUG/kpE6gFYsF.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, Image, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["ozxC7RAjO"];
var serializationHash = "framer-Rl6bU";
var variantClassNames = { ozxC7RAjO: "framer-v-19okerg" };
var transition1 = { damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring" };
var toResponsiveImage = (value) => {
  if (typeof value === "object" && value !== null && typeof value.src === "string") {
    return value;
  }
  return typeof value === "string" ? { src: value } : void 0;
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion(React.Fragment);
var getProps = ({ height, id, image, width, ...props }) => {
  return { ...props, cOxJ7FGW3: image !== null && image !== void 0 ? image : props.cOxJ7FGW3 };
};
var createLayoutDependency = (props, variants) => variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, cOxJ7FGW3, ...restProps } = getProps(props);
  const { baseVariant, classNames, gestureVariant, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "ozxC7RAjO", variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, className: cx(serializationHash, ...sharedStyleClassNames, "framer-19okerg", className, classNames), "data-framer-name": "Variant 1", layoutDependency, layoutId: "ozxC7RAjO", onHoverEnd: () => setGestureState({ isHovered: false }), onHoverStart: () => setGestureState({ isHovered: true }), onTap: () => setGestureState({ isPressed: false }), onTapCancel: () => setGestureState({ isPressed: false }), onTapStart: () => setGestureState({ isPressed: true }), ref: ref !== null && ref !== void 0 ? ref : ref1, style: { backgroundColor: "rgb(255, 255, 255)", borderBottomLeftRadius: 96, borderBottomRightRadius: 96, borderTopLeftRadius: 96, borderTopRightRadius: 96, ...style }, children: /* @__PURE__ */ _jsx(Image, { background: { alt: "", fit: "fill", sizes: "32px", ...toResponsiveImage(cOxJ7FGW3) }, className: "framer-1esthy9", layoutDependency, layoutId: "PwEkgay2N", style: { borderBottomLeftRadius: 96, borderBottomRightRadius: 96, borderTopLeftRadius: 96, borderTopRightRadius: 96 } }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Rl6bU.framer-gq5whd, .framer-Rl6bU .framer-gq5whd { display: block; }", ".framer-Rl6bU.framer-19okerg { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 2px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-Rl6bU .framer-1esthy9 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 32px); overflow: hidden; position: relative; width: 32px; will-change: var(--framer-will-change-override, transform); }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Rl6bU.framer-19okerg { gap: 0px; } .framer-Rl6bU.framer-19okerg > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-Rl6bU.framer-19okerg > :first-child { margin-left: 0px; } .framer-Rl6bU.framer-19okerg > :last-child { margin-right: 0px; } }"];
var FramerkpE6gFYsF = withCSS(Component, css, "framer-Rl6bU");
var stdin_default = FramerkpE6gFYsF;
FramerkpE6gFYsF.displayName = "Memoji";
FramerkpE6gFYsF.defaultProps = { height: 36, width: 36 };
addPropertyControls(FramerkpE6gFYsF, { cOxJ7FGW3: { title: "Image", type: ControlType.ResponsiveImage } });
addFonts(FramerkpE6gFYsF, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:memoji
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes,
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: void 0,
      locale,
      locales
    }
  );
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes,
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: void 0,
      locale,
      locales
    }
  );
};
Object.assign(ComponentWithRoot, stdin_default);
var memoji_default = ComponentWithRoot;
export {
  memoji_default as default
};
