// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
"use client";
import {
  routes
} from "./chunks/chunk-VG7AXKTA.js";

// virtual:services-graphic
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/pp6c7A0xqIuuymkz0ozY/YQsH7WBOX89nteJkmalb/dQApjyJi7.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, Image, useComponentViewport, useLocaleInfo, useVariantState, withCSS, withFX } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var ImageWithFX = withFX(Image);
var cycleOrder = ["t5VOSUnDD"];
var serializationHash = "framer-VBR1P";
var variantClassNames = { t5VOSUnDD: "framer-v-v4mkyo" };
var transition1 = { damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring" };
var toResponsiveImage = (value) => {
  if (typeof value === "object" && value !== null && typeof value.src === "string") {
    return value;
  }
  return typeof value === "string" ? { src: value } : void 0;
};
var transition2 = { delay: 0, duration: 2.8, ease: [0, 0, 1, 1], type: "tween" };
var animation = { opacity: 1, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, x: 0, y: 24 };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion(React.Fragment);
var getProps = ({ height, id, image, rotation, width, ...props }) => {
  var _ref;
  return { ...props, f5o7dTxzX: rotation !== null && rotation !== void 0 ? rotation : props.f5o7dTxzX, ISp4bn5CL: (_ref = image !== null && image !== void 0 ? image : props.ISp4bn5CL) !== null && _ref !== void 0 ? _ref : { src: "https://framerusercontent.com/images/jaVohrUAKzleX6rjxEEOPrqeysw.png?scale-down-to=512", srcSet: "https://framerusercontent.com/images/jaVohrUAKzleX6rjxEEOPrqeysw.png?scale-down-to=512 512w,https://framerusercontent.com/images/jaVohrUAKzleX6rjxEEOPrqeysw.png 1024w" } };
};
var createLayoutDependency = (props, variants) => variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ISp4bn5CL, f5o7dTxzX, ...restProps } = getProps(props);
  const { baseVariant, classNames, gestureVariant, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "t5VOSUnDD", variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, className: cx(serializationHash, ...sharedStyleClassNames, "framer-v4mkyo", className, classNames), "data-framer-name": "Variant 1", layoutDependency, layoutId: "t5VOSUnDD", onHoverEnd: () => setGestureState({ isHovered: false }), onHoverStart: () => setGestureState({ isHovered: true }), onTap: () => setGestureState({ isPressed: false }), onTapCancel: () => setGestureState({ isPressed: false }), onTapStart: () => setGestureState({ isPressed: true }), ref: ref !== null && ref !== void 0 ? ref : ref1, style: { ...style }, children: /* @__PURE__ */ _jsx(ImageWithFX, { __framer__loop: animation, __framer__loopEffectEnabled: true, __framer__loopRepeatDelay: 0, __framer__loopRepeatType: "mirror", __framer__loopTransition: transition2, __perspectiveFX: false, __smartComponentFX: true, __targetOpacity: 1, background: { alt: "", fit: "fill", intrinsicHeight: 1024, intrinsicWidth: 1024, pixelHeight: 1024, pixelWidth: 1024, sizes: (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw", ...toResponsiveImage(ISp4bn5CL) }, className: "framer-18re7xq", "data-framer-name": "yellow_cube", layoutDependency, layoutId: "M7WSXZS1m", style: { rotate: f5o7dTxzX } }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-VBR1P.framer-2upiya, .framer-VBR1P .framer-2upiya { display: block; }", ".framer-VBR1P.framer-v4mkyo { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 240px; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 240px; }", ".framer-VBR1P .framer-18re7xq { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 240px); overflow: visible; position: relative; width: 240px; z-index: 1; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-VBR1P.framer-v4mkyo { gap: 0px; } .framer-VBR1P.framer-v4mkyo > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-VBR1P.framer-v4mkyo > :first-child { margin-left: 0px; } .framer-VBR1P.framer-v4mkyo > :last-child { margin-right: 0px; } }"];
var FramerdQApjyJi7 = withCSS(Component, css, "framer-VBR1P");
var stdin_default = FramerdQApjyJi7;
FramerdQApjyJi7.displayName = "Services-Graphic";
FramerdQApjyJi7.defaultProps = { height: 240, width: 240 };
addPropertyControls(FramerdQApjyJi7, { ISp4bn5CL: { __defaultAssetReference: "data:framer/asset-reference,jaVohrUAKzleX6rjxEEOPrqeysw.png?originalFilename=yellow-cube.png&preferredSize=auto", title: "Image", type: ControlType.ResponsiveImage }, f5o7dTxzX: { defaultValue: 0, title: "Rotation", type: ControlType.Number, unit: "\xB0" } });
addFonts(FramerdQApjyJi7, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:services-graphic
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes,
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: void 0,
      locale,
      locales
    }
  );
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes,
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: void 0,
      locale,
      locales
    }
  );
};
Object.assign(ComponentWithRoot, stdin_default);
var services_graphic_default = ComponentWithRoot;
export {
  services_graphic_default as default
};
